type: object
required: [licensors]
properties:
  licensors:
    type: array
    items:
      type: object
      required: [name]
      properties:
        name:
          type: string
        url:
          type: string
          format: url
        products:
          type: array
          items:
            type: object
            required: [name]
            properties:
              name:
                type: string
              url:
                type: string
                format: url
              announcement:
                type: string
                format: url
  historic:
    type: array
    items:
      type: object
      required: [name, url]
      properties:
        name:
          type: string
        url:
          type: string
          format: url
      additionalProperties: false
additionalProperties: false
