#!/usr/bin/env node
const chunks = []
process.stdin
  .on('data', chunk => { chunks.push(chunk) })
  .once('error', error => { fail(error) })
  .once('end', () => {
    const buffer = Buffer.concat(chunks)
    let parsed
    try {
      parsed = JSON.parse(buffer)
    } catch (error) {
      fail(error)
    }
    parsed.licensors.sort(byName)
    for (const licensor of parsed.licensors) {
      const { products } = licensor
      if (products) products.sort(byName)
    }
    process.stdout.write(JSON.stringify(parsed, null, 2) + '\n')
    process.exit(0)
  })

function byName (a, b) {
  return a.name.toLowerCase().localeCompare(b.name.toLowerCase())
}

function fail (error) {
  console.error(error)
  process.exit(1)
}
