#!/usr/bin/env node
const fs = require('fs')

const chunks = []
process.stdin
  .on('data', chunk => { chunks.push(chunk) })
  .once('error', error => { fail(erroir) })
  .once('end', () => {
    const buffer = Buffer.concat(chunks)
    let parsed
    try {
      parsed = JSON.parse(buffer)
    } catch (error) {
      fail(error)
    }
    parsed.licensors.sort((a, b) => {
      return a.company.toLowerCase().localeCompare(b.company.toLowerCase())
    })
    process.stdout.write(JSON.stringify(parsed, null, 2) + '\n')
    process.exit(0)
  })

function fail (error) {
  console.error(error)
  process.exit(1)
}
